/run/initialize
/vis/open TSG
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year

/gps/particle ion
/gps/ion 27 60 0 0

/gps/pos/type Volume 
/gps/pos/shape Cylinder
/gps/pos/centre 0. 0. 12. cm
/gps/pos/radius 0.8 cm
/gps/pos/halfz 6. cm

/gps/ang/type iso